"""Deterministic Mock LLM.

Derives structured output from LLMRequest.context using lexicon-driven
heuristics -- never calls a real model, never invents evidence, and never
presents its output as coming from a real model. Same input always produces
the same output (no random, no time-dependence).
"""
import re
from typing import Any, TypeVar

from pydantic import BaseModel

from models.candidate import CandidateAnalysis, FitAnalysis
from models.common import EvaluationCategory, QuestionCategory
from models.evaluation import CategoryEvaluation
from models.interview import FollowUpDecision, InterviewPlan, InterviewQuestion, InterviewTurn
from models.job import JobAnalysis
from models.voice_intent import VoiceIntent, VoiceIntentResult
from services.candidate_name import extract_explicit_candidate_name
from services.llm.base import LLMError, LLMRequest, LLMService, UnsupportedTaskError
from services.llm.mock import heuristics as h

T = TypeVar("T", bound=BaseModel)

MOCK_DISCLAIMER = "Demo / Mock Mode: this output was generated by a deterministic local heuristic, not an LLM."

_TECHNOLOGY_TERMS = {
    "python", "java", "javascript", "sql", "nosql", "machine_learning", "deep_learning",
    "nlp", "llm", "rag", "vector_database", "retrieval", "api_development", "cloud",
    "containers", "data_engineering", "version_control", "testing",
}
_COMPETENCY_TERMS = {"communication", "leadership", "problem_solving"}
_VALIDATION_WORTHY_TERMS = {
    "rag", "llm", "deep_learning", "system_design", "data_engineering",
    "retrieval", "vector_database", "cloud", "containers",
}
_NICE_TO_HAVE_MARKERS = ("nice to have", "nice-to-have", "preferred", "bonus", "a plus")

_RESPONSIBILITY_PATTERN = re.compile(
    r"\b(build|design|develop|implement|maintain|collaborat\w*|analy[sz]e|create|"
    r"support|own|drive|lead|manage|write|deploy|optimi[sz]e|research)\b",
    re.IGNORECASE,
)
_EXPERIENCE_PATTERN = re.compile(r"\b\d+\+?\s*(years?|yrs?)\b", re.IGNORECASE)
_PROJECT_PATTERN = re.compile(
    r"\b(built|developed|created|implemented|designed|led|shipped|launched)\b", re.IGNORECASE
)
_EDUCATION_PATTERN = re.compile(
    r"\b(bachelor|master|phd|b\.sc|m\.sc|university|college|degree)\b", re.IGNORECASE
)
# ---- small shared helpers ----

def _get_field(source: Any, key: str, default: Any = None) -> Any:
    if isinstance(source, BaseModel):
        return getattr(source, key, default)
    if isinstance(source, dict):
        return source.get(key, default)
    return default


def _dedup(items: list[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for item in items:
        if item not in seen:
            seen.add(item)
            result.append(item)
    return result


def _display_label(canonical: str) -> str:
    if canonical == "api_development":
        return "API Development"
    if canonical in {"nlp", "sql", "rag", "llm"}:
        return canonical.upper()
    return canonical.replace("_", " ").title()


def _coerce_turn(value: Any) -> InterviewTurn:
    if isinstance(value, InterviewTurn):
        return value
    return InterviewTurn.model_validate(value)


def _coerce_category(value: Any) -> EvaluationCategory:
    if isinstance(value, EvaluationCategory):
        return value
    return EvaluationCategory(value)


# ---- job_analysis ----

def _split_required_vs_nice(text: str, terms: list[str]) -> tuple[list[str], list[str]]:
    lower = text.lower()
    split_index = len(text)
    for marker in _NICE_TO_HAVE_MARKERS:
        idx = lower.find(marker)
        if idx != -1:
            split_index = min(split_index, idx)
    if split_index == len(text):
        return list(terms), []
    before_terms = set(h.extract_terms(text[:split_index]))
    required = [t for t in terms if t in before_terms]
    nice_to_have = [t for t in terms if t not in before_terms]
    return required, nice_to_have


def _build_job_analysis(context: dict[str, Any]) -> JobAnalysis:
    job_title = str(_get_field(context, "job_title", "")).strip() or "the role"
    experience_level = _get_field(context, "experience_level")
    experience_level = str(experience_level) if experience_level else None
    description_text = str(_get_field(context, "description_text", ""))

    terms = h.extract_terms(description_text)
    technical_terms = [t for t in terms if t not in _COMPETENCY_TERMS]
    competency_terms = [t for t in terms if t in _COMPETENCY_TERMS]

    required, nice_to_have = _split_required_vs_nice(description_text, technical_terms)
    required_labels = [_display_label(t) for t in required]
    nice_to_have_labels = [_display_label(t) for t in nice_to_have]
    technical_labels = [_display_label(t) for t in technical_terms]
    behavioral_labels = [_display_label(t) for t in competency_terms]

    sentences = h.split_sentences(description_text)
    responsibilities = _dedup([s for s in sentences if _RESPONSIBILITY_PATTERN.search(s)])[:6]

    top_topics = technical_labels[:3]
    focus = f" Focus areas include {', '.join(top_topics)}." if top_topics else ""
    level_suffix = f" ({experience_level})" if experience_level else ""
    role_summary = f"{job_title}{level_suffix} role.{focus}".strip()

    return JobAnalysis(
        job_title=job_title,
        experience_level=experience_level,
        required_skills=required_labels,
        nice_to_have_skills=nice_to_have_labels,
        responsibilities=responsibilities,
        technical_topics=technical_labels,
        behavioral_competencies=behavioral_labels,
        role_summary=role_summary,
    )


# ---- candidate_analysis ----

def _build_candidate_analysis(context: dict[str, Any]) -> CandidateAnalysis:
    cv_text = str(_get_field(context, "cv_text", ""))
    terms = h.extract_terms(cv_text)
    skills = [_display_label(t) for t in terms]
    technologies = [_display_label(t) for t in terms if t in _TECHNOLOGY_TERMS]

    sentences = h.split_sentences(cv_text)
    experience = _dedup([s for s in sentences if _EXPERIENCE_PATTERN.search(s)])[:6]
    projects = _dedup([s for s in sentences if _PROJECT_PATTERN.search(s)])[:6]
    education = _dedup([s for s in sentences if _EDUCATION_PATTERN.search(s)])[:4]

    ranked = sorted(
        ((h.specificity(s), s) for s in sentences if len(s) >= 15),
        key=lambda pair: (-pair[0], pair[1]),
    )
    important_claims = _dedup([s for _, s in ranked])[:5]
    unclear_claims = _dedup([
        s for s in important_claims
        if any(term in _VALIDATION_WORTHY_TERMS for term in h.extract_terms(s))
    ])

    return CandidateAnalysis(
        full_name=extract_explicit_candidate_name(cv_text),
        skills=skills,
        technologies=technologies,
        experience=experience,
        projects=projects,
        education=education,
        important_cv_claims=important_claims,
        relevant_experience=experience,
        unclear_claims_to_validate=unclear_claims,
    )


# ---- fit_analysis ----

def _build_fit_analysis(context: dict[str, Any]) -> FitAnalysis:
    job_analysis = _get_field(context, "job_analysis", {})
    candidate_analysis = _get_field(context, "candidate_analysis", {})

    job_required = list(_get_field(job_analysis, "required_skills", []) or [])
    job_nice = list(_get_field(job_analysis, "nice_to_have_skills", []) or [])
    job_all = _dedup(job_required + job_nice)

    candidate_skills = list(_get_field(candidate_analysis, "skills", []) or [])
    candidate_tech = list(_get_field(candidate_analysis, "technologies", []) or [])
    candidate_all = set(_dedup(candidate_skills + candidate_tech))

    strong_alignment = [s for s in job_all if s in candidate_all]
    missing_information = [s for s in job_required if s not in candidate_all]

    relevant_experience = list(
        _get_field(candidate_analysis, "relevant_experience", [])
        or _get_field(candidate_analysis, "experience", [])
        or []
    )
    unclear_claims = list(_get_field(candidate_analysis, "unclear_claims_to_validate", []) or [])
    important_claims = list(_get_field(candidate_analysis, "important_cv_claims", []) or [])
    questions_to_investigate = [f"Ask the candidate to elaborate on: {claim}" for claim in important_claims[:5]]

    return FitAnalysis(
        strong_alignment_areas=strong_alignment,
        relevant_candidate_experience=relevant_experience,
        important_job_requirements=job_required,
        skills_requiring_validation=unclear_claims,
        missing_information=missing_information,
        questions_to_investigate=questions_to_investigate,
    )


# ---- interview_planning ----

_CATEGORY_ROTATION = [
    QuestionCategory.CV_PROJECT_VALIDATION,
    QuestionCategory.TECHNICAL,
    QuestionCategory.PROBLEM_SOLVING,
    QuestionCategory.BEHAVIORAL,
    QuestionCategory.CANDIDATE_BACKGROUND,
]
_POSITION_CATEGORY_ROTATION = [
    QuestionCategory.TECHNICAL,
    QuestionCategory.PROBLEM_SOLVING,
    QuestionCategory.BEHAVIORAL,
    QuestionCategory.CANDIDATE_BACKGROUND,
]
_DIFFICULTY_BY_LEVEL = {
    "Intern": "easy", "Junior": "easy", "Mid-Level": "medium",
    "Senior": "hard", "Lead": "hard", "Principal": "hard", "Executive": "hard",
}


_METRIC_PATTERN = re.compile(r"\d")
_SENTENCE_SPLIT = re.compile(r"(?<=[.!?])\s+|\n+")
_MAX_SEED_CHARS = 180


def _clean_claim(raw: str) -> str:
    """Reduce a raw CV excerpt to one quotable sentence.

    Extracted claims can arrive as multi-line blocks (a heading plus bullets),
    which quoted verbatim produce an unreadable question. Take the most
    informative single sentence instead, preferring one that carries a number --
    a measurable result is the most checkable thing a CV offers.
    """
    fragments = [
        fragment.strip(" \t-•*").strip()
        for fragment in _SENTENCE_SPLIT.split(raw)
        if fragment and fragment.strip(" \t-•*").strip()
    ]
    if not fragments:
        return raw.strip()[:_MAX_SEED_CHARS]
    # Ignore all-caps section headings like "EXPERIENCE" -- they are not claims.
    substantive = [f for f in fragments if not (f.isupper() and len(f.split()) <= 3)]
    candidates = substantive or fragments
    with_metric = [f for f in candidates if _METRIC_PATTERN.search(f)]
    chosen = (with_metric or candidates)[0]
    return chosen[:_MAX_SEED_CHARS].rstrip(" ,;:")


def _cv_validation_question(seed: str, _idx: int) -> tuple[str, str, list[str]]:
    claim = _clean_claim(seed)
    if _METRIC_PATTERN.search(claim):
        question = (
            f'Your CV mentions: "{claim}" What did you change to achieve that result?'
        )
        purpose = "Validate a measurable CV claim and the reasoning behind the result."
    else:
        question = (
            f'Your CV mentions: "{claim}" What was your specific role?'
        )
        purpose = "Validate a specific claim from the candidate's CV with concrete detail."
    seed = claim
    # expected_topics drives follow-up coverage checking, which is keyword-based --
    # the raw claim sentence itself is a poor fit for that (a good elaboration answer
    # naturally uses different words for the same story). Use the claim's own
    # lexicon-recognized keywords instead, falling back to the raw sentence only if
    # the claim contains no recognizable keyword at all.
    keyword_topics = [_display_label(t) for t in h.extract_terms(seed)]
    expected_topics = keyword_topics or [seed]
    return question, purpose, expected_topics


def _technical_question(seed: str, _idx: int) -> tuple[str, str, list[str]]:
    question = f"What is the most demanding thing you have built with {seed}?"
    purpose = f"Assess depth of technical knowledge in {seed}, a requirement for this role."
    return question, purpose, [seed]


def _gap_question(seed: str, _idx: int) -> tuple[str, str, list[str]]:
    """For a JD requirement the CV does not evidence.

    Deliberately neutral: a CV being silent about a skill is not evidence the
    candidate lacks it, so this asks about exposure rather than implying a
    deficiency.
    """
    question = (
        f"{seed} is important for this role, and I did not see much about it on your CV. "
        f"What exposure have you had to it?"
    )
    purpose = (
        f"Probe a job requirement not evidenced in the CV: {seed}. The CV's silence is "
        f"not evidence of absence -- this establishes the real level of exposure."
    )
    return question, purpose, [seed]


def _problem_solving_question(seed: str, _idx: int) -> tuple[str, str, list[str]]:
    focus = _clean_claim(seed)
    question = f"Tell me about a problem you solved while working on {focus}."
    purpose = "Assess problem-solving approach and reasoning process."
    seed = focus
    # Same reasoning as _cv_validation_question: seed here is often a full JD
    # responsibility sentence, which is a poor fit for keyword-based coverage checking.
    keyword_topics = [_display_label(t) for t in h.extract_terms(seed)]
    expected_topics = keyword_topics or [seed]
    return question, purpose, expected_topics


def _behavioral_question(seed: str, _idx: int) -> tuple[str, str, list[str]]:
    # Competency labels arrive title-cased for display ("Communication"); mid-sentence
    # they should read as ordinary prose, so lower the case of single-word labels.
    spoken = seed.lower() if seed.isalpha() else seed
    question = f"Tell me about a specific situation where {spoken} really mattered to the outcome."
    purpose = f"Assess the behavioral competency: {seed}."
    return question, purpose, [seed]


def _background_question(seed: str, _idx: int) -> tuple[str, str, list[str]]:
    question = f"Tell me about {seed}."
    purpose = "Understand candidate background and motivation relevant to the role."
    return question, purpose, []


_QUESTION_TEMPLATES = {
    QuestionCategory.CV_PROJECT_VALIDATION: _cv_validation_question,
    QuestionCategory.TECHNICAL: _technical_question,
    QuestionCategory.PROBLEM_SOLVING: _problem_solving_question,
    QuestionCategory.BEHAVIORAL: _behavioral_question,
    QuestionCategory.CANDIDATE_BACKGROUND: _background_question,
}


def _normalize_question(text: str) -> str:
    """Comparison key for duplicate detection: case- and punctuation-insensitive."""
    return re.sub(r"[^a-z0-9 ]+", "", text.casefold()).strip()


def _jd_gaps(job_analysis: Any, candidate_analysis: Any) -> list[str]:
    """Job requirements with no matching evidence anywhere in the candidate analysis.

    Compared on the lexicon's normalized terms so "Vector Database" on the JD
    matches "vector databases" on the CV rather than looking like a gap.
    """
    required = list(_get_field(job_analysis, "required_skills", []) or []) + list(
        _get_field(job_analysis, "technical_topics", []) or []
    )
    evidenced_text = " ".join(
        str(item)
        for field in ("skills", "technologies", "experience", "projects", "important_cv_claims")
        for item in (_get_field(candidate_analysis, field, []) or [])
    )
    evidenced_terms = set(h.extract_terms(evidenced_text))
    gaps: list[str] = []
    for requirement in required:
        requirement_terms = set(h.extract_terms(str(requirement)))
        # No recognizable terms means we cannot judge coverage -- don't guess a gap.
        if requirement_terms and not (requirement_terms & evidenced_terms):
            gaps.append(str(requirement))
    return _dedup(gaps)


def _build_interview_plan(context: dict[str, Any]) -> InterviewPlan:
    position_baseline = _get_field(context, "scope") == "position_baseline"
    if position_baseline:
        forbidden_keys = {
            "candidate_id",
            "candidate_name",
            "candidate_cv_text",
            "candidate_analysis",
            "fit_analysis",
            "candidate_interview_plan",
        }.intersection(context)
        if forbidden_keys:
            raise LLMError(
                "Position baseline planning context cannot contain candidate-specific fields."
            )

    job_title = str(_get_field(context, "job_title", "") or "the role")
    company_name = str(_get_field(context, "company_name", "") or "the company")
    experience_level = _get_field(context, "experience_level")
    num_questions = int(_get_field(context, "num_questions", 6) or 6)
    job_analysis = _get_field(context, "job_analysis", {})
    candidate_analysis = _get_field(context, "candidate_analysis", {})
    fit_analysis = _get_field(context, "fit_analysis", {})

    existing_questions = list(_get_field(context, "existing_questions", []) or [])

    n = max(num_questions, 3)
    difficulty = _DIFFICULTY_BY_LEVEL.get(str(experience_level), "medium")
    # Seeded with the position's baseline bank so generated questions never restate
    # something the candidate would already be asked.
    seen_questions: set[str] = {_normalize_question(q) for q in existing_questions}

    questions: list[InterviewQuestion] = []
    if not position_baseline:
        questions.append(InterviewQuestion(
            id="q-intro-1",
            category=QuestionCategory.INTRODUCTION,
            question="Could you briefly introduce yourself?",
            purpose="Warm-up and initial rapport; establish the candidate's framing of their own fit.",
            expected_topics=[],
            difficulty="easy",
            follow_up_allowed=False,
        ))
        seen_questions.add(_normalize_question(questions[0].question))

    # Extracted (candidate/job-specific) seeds are always preferred; each category also
    # gets a small pool of generic fallback seeds so a plan can still reach the requested
    # question count without ever repeating a seed -- and therefore a question -- within
    # the same category once its specific content runs out.
    # CV claims carrying a measurable result come first: they are the most
    # checkable thing on a CV, so they make the strongest validation questions.
    cv_claims = [] if position_baseline else _dedup([
        _clean_claim(str(claim))
        for claim in (
            list(_get_field(candidate_analysis, "unclear_claims_to_validate", []) or [])
            + list(_get_field(candidate_analysis, "important_cv_claims", []) or [])
        )
    ])
    cv_claims.sort(key=lambda claim: 0 if _METRIC_PATTERN.search(claim) else 1)

    gaps = [] if position_baseline else _jd_gaps(job_analysis, candidate_analysis)

    extracted_pools: dict[QuestionCategory, list[str]] = {
        QuestionCategory.TECHNICAL: _dedup(
            ([] if position_baseline else gaps + list(
                _get_field(fit_analysis, "missing_information", []) or []
            ))
            + list(_get_field(job_analysis, "technical_topics", []) or [])
            + list(_get_field(job_analysis, "required_skills", []) or [])
        ),
        QuestionCategory.PROBLEM_SOLVING: list(
            _get_field(job_analysis, "responsibilities", []) or []
        ),
        QuestionCategory.BEHAVIORAL: list(
            _get_field(job_analysis, "behavioral_competencies", []) or []
        ),
        QuestionCategory.CANDIDATE_BACKGROUND: [],
    }
    if not position_baseline:
        extracted_pools[QuestionCategory.CV_PROJECT_VALIDATION] = cv_claims
    gap_seeds = set(gaps)
    fallback_pools: dict[QuestionCategory, list[str]] = {
        QuestionCategory.CV_PROJECT_VALIDATION: [
            "a project you are particularly proud of",
            "a technical decision you made that you would revisit differently today",
        ],
        QuestionCategory.TECHNICAL: [
            f"a technology or tool you would expect to use as a {job_title}",
            "how you approach learning a new technology quickly",
            "how you stay current with relevant technical developments",
        ],
        QuestionCategory.PROBLEM_SOLVING: [
            "a time you had to solve a technical problem under a tight deadline",
            "a time you had to debug a difficult issue",
            "a time you had to make a technical trade-off with limited information",
        ],
        QuestionCategory.BEHAVIORAL: [
            "teamwork under pressure",
            "handling a missed deadline",
            "resolving a disagreement with a teammate",
        ],
        QuestionCategory.CANDIDATE_BACKGROUND: [
            f"your background and experience relevant to {job_title}",
            "what draws you to this particular role",
            "how your recent work connects to this position",
        ],
    }
    if position_baseline:
        fallback_pools = {
            QuestionCategory.TECHNICAL: [
                f"the core tools used by a {job_title}",
                "designing maintainable technical solutions",
                "testing and production reliability",
                "learning a role-critical technology quickly",
            ],
            QuestionCategory.PROBLEM_SOLVING: [
                "a difficult production issue",
                "a technical trade-off with limited information",
                "a delivery risk under a tight deadline",
                "an ambiguous requirement",
            ],
            QuestionCategory.BEHAVIORAL: [
                "teamwork under pressure",
                "handling a missed deadline",
                "resolving a disagreement with a teammate",
                "communicating a technical risk to stakeholders",
            ],
            QuestionCategory.CANDIDATE_BACKGROUND: [
                f"your experience relevant to the {job_title} role",
                "the work environment where you are most effective",
                "what interests you about this type of role",
                "the responsibilities you would like to deepen next",
            ],
        }
    category_rotation = (
        _POSITION_CATEGORY_ROTATION if position_baseline else _CATEGORY_ROTATION
    )
    seed_pools: dict[QuestionCategory, list[str]] = {
        cat: _dedup(extracted_pools[cat] + fallback_pools[cat]) for cat in category_rotation
    }
    used_seeds: dict[QuestionCategory, set[str]] = {cat: set() for cat in category_rotation}
    counters = {cat: 0 for cat in category_rotation}

    specific_seeds: dict[QuestionCategory, set[str]] = {
        cat: set(extracted_pools[cat]) for cat in category_rotation
    }

    def _emit(category: QuestionCategory) -> bool:
        """Add one question for this category. Returns False when it has nothing
        left to say that would not repeat an existing question."""
        for seed in seed_pools[category]:
            if seed in used_seeds[category]:
                continue
            template = (
                _gap_question
                if category is QuestionCategory.TECHNICAL and seed in gap_seeds
                else _QUESTION_TEMPLATES[category]
            )
            question_text, purpose, expected_topics = template(seed, counters[category] + 1)
            key = _normalize_question(question_text)
            if key in seen_questions:
                # Two different seeds can phrase to the same question; skip, don't
                # burn the slot on a duplicate.
                used_seeds[category].add(seed)
                continue
            used_seeds[category].add(seed)
            seen_questions.add(key)
            counters[category] += 1
            questions.append(InterviewQuestion(
                id=f"q-{category.value}-{counters[category]}",
                category=category,
                question=question_text,
                purpose=purpose,
                expected_topics=expected_topics,
                difficulty=difficulty,
                follow_up_allowed=True,
            ))
            return True
        return False

    remaining = n if position_baseline else n - 2  # candidate plans include intro/closing

    # Guarantee a balanced plan first: one technical, one problem-solving and one
    # behavioural question before anything else competes for the remaining slots,
    # so a CV rich in claims cannot crowd out whole dimensions of the interview.
    for category in (
        QuestionCategory.TECHNICAL,
        QuestionCategory.PROBLEM_SOLVING,
        QuestionCategory.BEHAVIORAL,
    ):
        if remaining <= 0:
            break
        if _emit(category):
            remaining -= 1

    # Then spend everything else on candidate-specific material before generic
    # fallbacks: a question grounded in this candidate's CV always beats a
    # template question that would suit any applicant.
    for prefer_specific in (True, False):
        rotation_pos = 0
        stalled = 0
        while remaining > 0 and stalled < len(category_rotation):
            category = category_rotation[rotation_pos % len(category_rotation)]
            rotation_pos += 1
            has_unused_specific = any(
                seed in specific_seeds[category] and seed not in used_seeds[category]
                for seed in seed_pools[category]
            )
            if prefer_specific and not has_unused_specific:
                stalled += 1
                continue
            if _emit(category):
                remaining -= 1
                stalled = 0
            else:
                stalled += 1

    if not position_baseline:
        questions.append(InterviewQuestion(
            id="q-closing-1",
            category=QuestionCategory.CLOSING,
            question=(
                f"Before we wrap up, what questions do you have about the role, the team, "
                f"or {company_name}?"
            ),
            purpose="Give the candidate an opportunity to ask questions; assess engagement.",
            expected_topics=[],
            difficulty="easy",
            follow_up_allowed=False,
        ))
    return InterviewPlan(questions=questions)


# ---- follow_up ----

_REFUSAL_MARKERS = (
    "don't know", "do not know", "dont know", "not sure", "no idea", "n/a",
    "no experience with that", "not familiar with that",
    "prefer not to answer", "skip this",
)


def _looks_like_refusal(answer: str) -> bool:
    lower = answer.strip().lower()
    if not lower:
        return True
    return any(lower == marker or (len(lower.split()) <= 6 and marker in lower) for marker in _REFUSAL_MARKERS)


def _decide_follow_up(context: dict[str, Any]) -> FollowUpDecision:
    question = _get_field(context, "question", {})
    expected_topics = list(_get_field(question, "expected_topics", []) or [])
    follow_up_allowed = bool(_get_field(question, "follow_up_allowed", True))
    latest_answer = str(_get_field(context, "latest_answer", ""))
    raw_turns_so_far = list(_get_field(context, "turns_so_far", []) or [])
    turns_so_far = [_coerce_turn(t) for t in raw_turns_so_far]

    if not follow_up_allowed:
        return FollowUpDecision(should_ask=False, reason="This question's category does not use follow-ups.")
    if _looks_like_refusal(latest_answer):
        return FollowUpDecision(
            should_ask=False,
            reason="Answer was empty or a refusal; probing further would not be productive.",
        )

    # Evaluate coverage/specificity against the full conversation for this question so
    # far, not just the latest fragment -- otherwise a topic covered in an earlier
    # answer could look "missing" again once a later, narrower answer is considered alone.
    cumulative_answer = " ".join(
        [t.answer for t in turns_so_far if t.answer and t.answer.strip()] + [latest_answer]
    ).strip()

    cov = h.coverage(cumulative_answer, expected_topics)
    spec = h.specificity(cumulative_answer)
    if cov >= 0.7 and spec >= 0.6:
        return FollowUpDecision(
            should_ask=False,
            reason=f"Answer already covers the expected topics with good specificity "
                   f"(coverage={cov:.2f}, specificity={spec:.2f}).",
        )

    missing = [t for t in expected_topics if not h.topic_mentioned(cumulative_answer, t)]
    if missing:
        target = missing[0]
        # A short topic phrase ("vector database") reads naturally inline; a long,
        # sentence-like target (e.g. a full CV claim used as its own expected_topic)
        # needs to be quoted instead, or the question comes out as a run-on artifact.
        if len(target) > 60 or target.rstrip().endswith((".", "!", "?")):
            quoted = target.rstrip(".! ")
            follow_up_question = f'You mentioned: "{quoted}" Can you go into more specific detail about that?'
        else:
            follow_up_question = f"Can you go into more detail about {target}?"
        reason = f"The answer did not clearly address expected topic: {target}."
    elif spec < 0.6:
        terms = h.extract_terms(cumulative_answer)
        if terms:
            follow_up_question = (
                f"Can you give a concrete example, including specifics like tools or "
                f"outcomes, of your work with {_display_label(terms[0])}?"
            )
        else:
            follow_up_question = "Can you give a more concrete example, with specific details or outcomes?"
        reason = f"The answer was general; low specificity score ({spec:.2f})."
    else:
        return FollowUpDecision(
            should_ask=False,
            reason="Answer is adequately specific and no expected topics are clearly missing.",
        )

    return FollowUpDecision(should_ask=True, follow_up_question=follow_up_question, reason=reason)


# ---- voice_intent ----

# Broader than the engine's own regex fast path on purpose: Mock Mode must
# demonstrate the same don't-know/refusal understanding Phase 1 ships for real
# providers, using a deterministic heuristic lexicon instead of a live model
# (docs/ARCHITECTURE.md: Mock Mode completes the whole flow with no API key, and never
# presents its output as a real model response).
_MOCK_DONT_KNOW_MARKERS = (
    "don't know", "do not know", "dont know",
    "don't remember", "do not remember", "dont remember",
    "don't recall", "do not recall", "dont recall",
    "not sure", "no idea", "n/a",
    "not familiar with", "no experience with", "don't have experience",
    "do not have experience", "haven't worked with", "have not worked with",
    "haven't used", "have not used", "never worked with", "never used",
    "haven't had the chance", "have not had the chance",
    "not something i've worked on", "not something i have worked on",
    "skip this",
)
_MOCK_REFUSAL_MARKERS = (
    "prefer not to answer", "rather not say", "rather not discuss",
    "rather not answer", "not comfortable", "prefer not to say",
    "prefer not to discuss",
)
# Covers the same markers with an inserted hedge word ("don't really have
# experience", "haven't really worked with") that a plain substring list would
# miss -- deliberately simple regexes, not a real language model, but sufficient
# for Mock Mode's deterministic-heuristic contract.
_MOCK_DONT_KNOW_REGEXES = tuple(re.compile(p) for p in (
    r"\bdo\s?n'?t\s+(?:really\s+)?know\b",
    r"\bdo\s+not\s+(?:really\s+)?know\b",
    r"\bhave\s?n'?t\s+(?:really\s+)?(?:worked|used|had)\b",
    r"\bhave\s+not\s+(?:really\s+)?(?:worked|used|had)\b",
    r"\bdo\s?n'?t\s+(?:really\s+)?have\s+experience\b",
    r"\bdo\s+not\s+(?:really\s+)?have\s+experience\b",
))
_MOCK_HEDGE_PIVOTS = (" but ", " although ", " though ", " however ")
_MOCK_MIN_SUBSTANCE_WORDS_AFTER_PIVOT = 3

# ---- Phase 3 mock parity: meta-intent detection ------------------------------
# Deterministic heuristics standing in for the real classifier's semantic
# understanding, so Mock Mode demonstrates the full Phase 3 dispatch with no API
# key (docs/ARCHITECTURE.md invariant). Deliberately simple; the real provider does
# the heavy lifting in production.
_MOCK_REPEAT_MARKERS = (
    "say that again", "repeat the question", "repeat that", "come again",
    "what was the question", "what was that again", "didn't catch", "did not catch",
    "didn't hear", "did not hear", "missed the question", "one more time",
    "what did you say",
)
_MOCK_REPHRASE_MARKERS = (
    "rephrase", "reword", "differently", "what do you mean", "don't understand",
    "do not understand", "doesn't make sense", "does not make sense", "confused",
    "explain the question", "clarify the question", "unfamiliar with the wording",
)
_MOCK_CONNECTION_MARKERS = (
    "can you hear me", "can anyone hear me", "are you there", "are you still there",
    "is this working", "am i audible", "hello can you hear", "testing testing",
    "hear me ok", "is my mic working", "is my microphone working",
)
_MOCK_OFF_TOPIC_MARKERS = (
    "tell me a joke", "a joke", "the weather", "weather like", "play music",
    "favorite movie", "favourite movie", "football score", "last night's game",
    "who will win the election", "your favorite food",
)
# Hesitation: asks for a moment / thinking aloud, no answer content. Checked on
# short utterances only so a story that happens to contain "let me think" is
# not misrouted.
_MOCK_HESITATION_EXACT = (
    "let me think", "let me see", "hold on", "hold on a second", "hold on a sec",
    "bear with me", "give me a moment", "give me a second", "just a moment",
    "just a second", "one moment", "one sec", "hmm let me think", "thinking",
)
_MOCK_CANDIDATE_QUESTION_STARTERS = (
    "what", "when", "where", "who", "how", "why", "can you tell me about the",
    "could you tell me about the", "do you know the", "is there a",
    "will there be", "are there any", "does the company", "do employees",
)
_MOCK_CANDIDATE_QUESTION_TOPICS = (
    "salary", "pay", "paid", "compensation", "benefit", "benefits", "perks",
    "next step", "next steps", "outcome", "decision", "hiring process",
    "interview process", "process after this", "working hours", "hours",
    "schedule", "office", "location", "remote", "hybrid", "onsite", "relocat",
    "team size", "team structure", "the team", "company culture", "culture",
    "the role like", "position like", "job title", "start date", "notice period",
)

# Content-caused reaction pools (Phase 3). Picked deterministically from the
# utterance text -- never random -- and varied by content class so Mock Mode
# exhibits the same "reaction caused by what was said" behaviour as production.
_CONCRETE_EXAMPLE_REACTIONS = ("Good example.", "That makes sense.", "Got it.")
_PLAIN_ANSWER_REACTIONS = ("Got it.", "Understood.", "Okay, noted.")
_DONT_KNOW_REACTION = "No problem, let's move on."
_REFUSAL_REACTION = "Understood, we'll skip that."
_CATEGORY_SEGUES = {
    QuestionCategory.TECHNICAL: "Let's switch to the technical side.",
    QuestionCategory.PROBLEM_SOLVING: "Next, let's talk through some problem solving.",
    QuestionCategory.BEHAVIORAL: "Let's shift to how you work with others.",
    QuestionCategory.CV_PROJECT_VALIDATION: "Let's dig into your project experience.",
    QuestionCategory.CANDIDATE_BACKGROUND: "Let's talk a bit about your background.",
}


def _mock_pick(text: str, options: tuple[str, ...]) -> str:
    """Deterministic pool pick derived from the text itself (no random/no time)."""
    return options[sum(ord(char) for char in text) % len(options)]


def _mock_hedge_then_substance(normalized: str) -> bool:
    """A hedge followed by real content is an answer, not a refusal -- same
    principle as services/interview_engine.py's own pivot check, kept as an
    independent, simpler heuristic here so Mock Mode has no dependency on the
    engine's private helpers."""
    for pivot in _MOCK_HEDGE_PIVOTS:
        index = normalized.find(pivot)
        if index == -1:
            continue
        remainder = normalized[index + len(pivot):]
        if len(remainder.split()) >= _MOCK_MIN_SUBSTANCE_WORDS_AFTER_PIVOT:
            return True
    return False


def _classify_voice_intent(context: dict[str, Any]) -> VoiceIntentResult:
    latest_answer = str(_get_field(context, "latest_answer", ""))
    upcoming_category = _get_field(context, "upcoming_category")
    normalized = " ".join(latest_answer.strip().casefold().split())

    if normalized and not _mock_hedge_then_substance(normalized):
        if any(marker in normalized for marker in _MOCK_REFUSAL_MARKERS):
            return VoiceIntentResult(
                intent=VoiceIntent.GENUINE_REFUSAL,
                confidence=0.9,
                reaction=_REFUSAL_REACTION,
                transition=_mock_transition(upcoming_category),
            )
        if any(marker in normalized for marker in _MOCK_DONT_KNOW_MARKERS) or any(
            pattern.search(normalized) for pattern in _MOCK_DONT_KNOW_REGEXES
        ):
            return VoiceIntentResult(
                intent=VoiceIntent.DONT_KNOW,
                confidence=0.9,
                reaction=_DONT_KNOW_REACTION,
                transition=_mock_transition(upcoming_category),
            )

    # Phase 3 meta-intents, in specificity order. Each is a delivery-only
    # dispatch: the conversation layer never submits these as answers.
    if any(marker in normalized for marker in _MOCK_REPEAT_MARKERS):
        return VoiceIntentResult(intent=VoiceIntent.REPEAT_REQUEST, confidence=0.9)
    if any(marker in normalized for marker in _MOCK_REPHRASE_MARKERS):
        return VoiceIntentResult(intent=VoiceIntent.REPHRASE_REQUEST, confidence=0.9)
    if any(marker in normalized for marker in _MOCK_CONNECTION_MARKERS):
        return VoiceIntentResult(intent=VoiceIntent.CONNECTION_CHECK, confidence=0.95)
    if _looks_like_candidate_question(normalized):
        return VoiceIntentResult(intent=VoiceIntent.CANDIDATE_QUESTION, confidence=0.85)
    if any(marker in normalized for marker in _MOCK_OFF_TOPIC_MARKERS):
        return VoiceIntentResult(intent=VoiceIntent.OFF_TOPIC, confidence=0.85)
    # Hesitation only when the utterance is essentially nothing but a pause
    # request -- short enough that an answer containing "let me think" mid-story
    # still routes by its content.
    if len(normalized.split()) <= 6 and any(
        marker == normalized or normalized.startswith(f"{marker} ") or normalized.endswith(f" {marker}")
        for marker in _MOCK_HESITATION_EXACT
    ):
        return VoiceIntentResult(intent=VoiceIntent.HESITATION, confidence=0.9)

    question = _get_field(context, "question", {})
    expected_topics = list(_get_field(question, "expected_topics", []) or [])
    cov = h.coverage(latest_answer, expected_topics)
    spec = h.specificity(latest_answer)
    intent = VoiceIntent.SUBSTANTIVE_ANSWER if (cov >= 0.5 and spec >= 0.4) else VoiceIntent.PARTIAL_ANSWER
    reaction = (
        _mock_pick(normalized, _CONCRETE_EXAMPLE_REACTIONS)
        if h.specificity(latest_answer) >= 0.6
        else _mock_pick(normalized, _PLAIN_ANSWER_REACTIONS)
    )
    return VoiceIntentResult(
        intent=intent,
        confidence=0.7,
        reaction=reaction,
        transition=_mock_transition(upcoming_category),
    )


def _looks_like_candidate_question(normalized: str) -> bool:
    """Deterministic candidate-question heuristic for Mock Mode.

    A question ABOUT the role/process/company, not an answer that happens to
    start with a question word ("What I did there was...").
    """
    if not normalized:
        return False
    mentions_topic = any(topic in normalized for topic in _MOCK_CANDIDATE_QUESTION_TOPICS)
    starts_like_question = normalized.startswith(_MOCK_CANDIDATE_QUESTION_STARTERS)
    asks_directly = "?" in normalized and mentions_topic
    answer_shaped = normalized.startswith(("what i ", "what we ", "how i ", "how we ", "why i ", "why we "))
    return (starts_like_question and mentions_topic and not answer_shaped) or asks_directly


def _mock_transition(upcoming_category: Any) -> str | None:
    """Segue text for the category AFTER this one, when the caller supplied it."""
    if upcoming_category is None:
        return None
    try:
        category = QuestionCategory(str(upcoming_category))
    except ValueError:
        return None
    return _CATEGORY_SEGUES.get(category)


# ---- evaluation ----

def _evaluate_category(context: dict[str, Any]) -> CategoryEvaluation:
    category = _coerce_category(_get_field(context, "category"))
    expected_topics = list(_get_field(context, "expected_topics", []) or [])
    raw_turns = list(_get_field(context, "turns", []) or [])
    turns = [_coerce_turn(t) for t in raw_turns]

    combined_answers = " ".join(t.answer for t in turns if t.answer and t.answer.strip())
    evidence = h.pick_evidence(turns, limit=3)

    if not combined_answers.strip() or not evidence:
        return CategoryEvaluation(
            category=category,
            score=None,
            sufficient_evidence=False,
            reasoning=(
                "Insufficient evidence: the transcript does not contain a substantive "
                f"answer addressing {category.value.replace('_', ' ')}."
            ),
            evidence=[],
            areas_to_validate=list(expected_topics),
        )

    cov = h.coverage(combined_answers, expected_topics)
    spec = h.specificity(combined_answers)
    br = h.breadth(combined_answers)
    raw_score = 100 * (0.5 * cov + 0.35 * spec + 0.15 * br)
    score = max(0, min(100, round(raw_score)))

    areas_to_validate = [t for t in expected_topics if not h.topic_mentioned(combined_answers, t)]
    reasoning = (
        f"Coverage of expected topics: {cov:.0%}. Specificity of the answer(s): {spec:.0%}. "
        f"Breadth of related concepts mentioned: {br:.0%}."
    )
    return CategoryEvaluation(
        category=category,
        score=score,
        sufficient_evidence=True,
        reasoning=reasoning,
        evidence=evidence,
        areas_to_validate=areas_to_validate,
    )


# ---- dispatch tables ----

_TASK_SCHEMAS: dict[str, type[BaseModel]] = {
    "job_analysis": JobAnalysis,
    "candidate_analysis": CandidateAnalysis,
    "fit_analysis": FitAnalysis,
    "interview_planning": InterviewPlan,
    "follow_up": FollowUpDecision,
    "evaluation": CategoryEvaluation,
    "voice_intent": VoiceIntentResult,
}

_TASK_HANDLERS: dict[str, Any] = {
    "job_analysis": _build_job_analysis,
    "candidate_analysis": _build_candidate_analysis,
    "fit_analysis": _build_fit_analysis,
    "interview_planning": _build_interview_plan,
    "follow_up": _decide_follow_up,
    "evaluation": _evaluate_category,
    "voice_intent": _classify_voice_intent,
}


class MockLLMService(LLMService):
    def __init__(self) -> None:
        self.provider_name = "mock"
        self.is_mock = True

    def generate_structured(self, request: LLMRequest, schema: type[T]) -> T:
        if request.task not in _TASK_HANDLERS:
            raise UnsupportedTaskError(
                f"MockLLMService has no handler for task '{request.task}'. "
                f"Supported tasks: {sorted(_TASK_HANDLERS)}"
            )
        expected_schema = _TASK_SCHEMAS[request.task]
        if schema is not expected_schema:
            raise LLMError(
                f"Task '{request.task}' produces {expected_schema.__name__}, "
                f"but caller requested {schema.__name__}."
            )
        return _TASK_HANDLERS[request.task](request.context)

    def generate_text(self, request: LLMRequest) -> str:
        if request.task not in _TASK_HANDLERS:
            raise UnsupportedTaskError(
                f"MockLLMService has no handler for task '{request.task}'. "
                f"Supported tasks: {sorted(_TASK_HANDLERS)}"
            )
        result = _TASK_HANDLERS[request.task](request.context)
        return f"[{MOCK_DISCLAIMER}]\n{result.model_dump_json(indent=2)}"
