"""Pure-Python overall scoring and recommendation logic.

This module must never import anything from services.llm.* -- that is what
structurally guarantees the overall score and the final recommendation are
always computed here, in Python, from config/rubrics.json, and never
generated by an LLM.
"""
from config.rubric_config import RubricProfile, RubricThresholds
from models.common import RecommendationLevel, ScreeningOutcome
from models.evaluation import CategoryEvaluation, InterviewEvaluation
from services.logging_service import Event, log_event


def compute_overall_score(category_evaluations: list[CategoryEvaluation], profile: RubricProfile) -> int | None:
    """Weighted mean over scored categories only; unscored categories are excluded
    and the remaining weights are implicitly renormalized by dividing by their own
    weight sum rather than the profile's full 100."""
    scored = [ce for ce in category_evaluations if ce.score is not None]
    total_weight = sum(profile.weights[ce.category] for ce in scored)
    if total_weight <= 0:
        return None
    weighted_sum = sum(ce.score * profile.weights[ce.category] for ce in scored)
    return round(weighted_sum / total_weight)


def compute_evidence_coverage(category_evaluations: list[CategoryEvaluation], profile: RubricProfile) -> float:
    """Fraction of the rubric's total weight that was actually backed by evidence."""
    total_possible_weight = sum(profile.weights.values())
    if total_possible_weight <= 0:
        return 0.0
    scored = [ce for ce in category_evaluations if ce.score is not None]
    covered_weight = sum(profile.weights[ce.category] for ce in scored)
    return max(0.0, min(1.0, covered_weight / total_possible_weight))


def determine_recommendation(
    evidence_coverage: float, overall_score: int | None, thresholds: RubricThresholds,
) -> RecommendationLevel:
    if evidence_coverage < thresholds.min_evidence_coverage or overall_score is None:
        return RecommendationLevel.INSUFFICIENT_EVIDENCE_FROM_INTERVIEW
    if overall_score >= thresholds.strong_evidence_min_score:
        return RecommendationLevel.STRONG_EVIDENCE_FOR_HUMAN_REVIEW
    if overall_score >= thresholds.proceed_min_score:
        return RecommendationLevel.PROCEED_TO_DEEPER_TECHNICAL_ASSESSMENT
    return RecommendationLevel.REQUIRES_ADDITIONAL_VALIDATION


def determine_screening_outcome(
    evidence_coverage: float, overall_score: int | None, thresholds: RubricThresholds,
) -> ScreeningOutcome:
    """Deterministic INITIAL SCREENING result -- not a hiring decision.

    PASS/FAIL/NEEDS_REVIEW is a separate, independently configurable axis from
    RecommendationLevel above (see `pass_score_threshold`), computed from the same
    evidence-based score and coverage. NEEDS_REVIEW covers every case where the
    evidence itself is insufficient to say pass or fail; FAIL is only ever reached
    when there WAS sufficient evidence and the score fell short of the threshold.
    FAIL must never be treated as an autonomous rejection -- the human recruiter
    remains the final decision maker.
    """
    if evidence_coverage < thresholds.min_evidence_coverage or overall_score is None:
        return ScreeningOutcome.NEEDS_REVIEW
    if overall_score >= thresholds.pass_score_threshold:
        return ScreeningOutcome.PASS
    return ScreeningOutcome.FAIL


def build_interview_evaluation(
    category_evaluations: list[CategoryEvaluation],
    profile: RubricProfile,
    profile_name: str,
    thresholds: RubricThresholds,
    session_id: str | None = None,
) -> InterviewEvaluation:
    computed_score = compute_overall_score(category_evaluations, profile)
    evidence_coverage = compute_evidence_coverage(category_evaluations, profile)
    recommendation = determine_recommendation(evidence_coverage, computed_score, thresholds)
    screening_outcome = determine_screening_outcome(evidence_coverage, computed_score, thresholds)
    # A weighted mean over a small scored subset can look authoritative while most of
    # the rubric has no evidence. Keep the category scores, but publish no final overall
    # score until the configured evidence-coverage threshold is met.
    overall_score = (
        computed_score
        if evidence_coverage >= thresholds.min_evidence_coverage
        else None
    )

    evaluation = InterviewEvaluation(
        category_evaluations=category_evaluations,
        overall_score=overall_score,
        evidence_coverage=evidence_coverage,
        recommendation=recommendation,
        screening_outcome=screening_outcome,
        rubric_profile=profile_name,
    )
    log_event(
        Event.EVALUATION_COMPLETED,
        session_id=session_id,
        overall_score=overall_score,
        evidence_coverage=evidence_coverage,
        recommendation=recommendation.value,
        screening_outcome=screening_outcome.value,
        rubric_profile=profile_name,
        categories_scored=sum(1 for ce in category_evaluations if ce.score is not None),
        categories_total=len(category_evaluations),
    )
    return evaluation
